Load libraries
```{r}
library(broom)
library(cowplot)
library(tidyverse)
```

Generate a data frame with the full names of all the variables profiled
```{r}
alt.names <- tribble(
  ~Variable, ~Variable2,
  "pH_Soil", "Soil pH",
  "pH_Buffer", "Buffer pH",
  "Soluble_Salts", "Soluble salts (mmho/cm)",
  "Lime", "Excess lime",
  "Texture", "Texture No",
  "OM", "Organic Matter (LOI %)",
  "Nitrate", "Nitrate (ppm)",
  "lbs", "lbs",
  "Phosphorus", "Phosphorus (ppm)",
  "Potassium", "Potassium (ppm)",
  "Sulfate", "Sulfate (ppm)",
  "Zinc", "Zinc (ppm)",
  "Iron", "Iron (ppm)",
  "Manganese", "Manganese (ppm)",
  "Copper", "Copper (ppm)",
  "Calcium", "Calcium (ppm)",
  "Magnesium", "Magnesium (ppm)",
  "Sodium", "Sodium (ppm)",
  "Boron", "Boron (ppm)",
  "CEC", "CEC (meq/100g)",
  "H_Sat", "%H Sat.",
  "K_Sat", "%K Sat.",
  "Ca_Sat", "%Ca Sat.",
  "Mg_Sat", "%Mg Sat.",
  "Na_Sat", "%Na Sat."
)
```

Load data
```{r}
#Load soil nutrient data
ward <- read.table("../Data/nutrients.tsv", header = T, sep = "\t")

#Load mapping file
map <- readRDS("../Data/map.RDS") %>% 
  rename("SampleID" = "ViromeSampleID")
```

Environmental distance analysis
```{r}
#Remove variables with no variation, z-transform each variable, and format it as a matrix
nut.mtx <- ward %>% 
  select(-Lime, -Texture, -H_Sat, -pH_Buffer, -Ca_Sat, -K_Sat, -Na_Sat, -Mg_Sat, -lbs) %>% 
  gather(key = "Variable", value = "Value", -SampleID) %>% 
  group_by(Variable) %>% 
  mutate(zValue = (Value - mean(Value))/sd(Value)) %>% 
  select(SampleID, Variable, zValue) %>% 
  spread(key = Variable, value = zValue) %>% 
  as.data.frame()
row.names(nut.mtx) <- nut.mtx$SampleID
nut.mtx <- nut.mtx[,-1]
nut.mtx <- as.matrix(nut.mtx)

#Calculate the environmental distance and filter redundant values
nut.dist <- as.matrix(dist(nut.mtx, method = "euclidean"))
nut.dist[upper.tri(nut.dist)] <- NA 

#Create a long data frame and remove pairwise comparisons between the same sample
nut.dist.tidy <- nut.dist %>% 
  as.data.frame() %>% 
  mutate(SampleID.x = row.names(.)) %>% 
  gather(key = "SampleID.y", value = "EucDist", -SampleID.x) %>% 
  filter(!is.na(EucDist)) %>% 
  filter(SampleID.x != SampleID.y) %>% 
  inner_join(map, by = c("SampleID.x" = "SampleID")) %>% 
  inner_join(map, by = c("SampleID.y" = "SampleID")) %>% 
  mutate(SpatialDistance = sqrt((Position.x.x - Position.x.y)^2 + (Position.y.x - Position.y.y)^2))

#Perform correlation analysis and regression 
cor <- cor.test(nut.dist.tidy$SpatialDistance, nut.dist.tidy$EucDist, method = "pearson", alternative = "two.sided") %>% tidy()
lm <- lm(EucDist ~ SpatialDistance, data = nut.dist.tidy) %>% tidy() %>% filter(term == "SpatialDistance")
dist.stats <- data.frame(label = paste("r = ", signif(cor$estimate,3), 
                                       "\nslope = ", signif(lm$estimate, 3),
                                       "\nP = ", signif(cor$p.value, 3)))
  
#Plot
environmental.p <- nut.dist.tidy %>% 
  ggplot(aes(SpatialDistance, EucDist)) +
  geom_point(shape = 16, size = 1, alpha = 0.5, color = "gray25") +
  geom_text(data = dist.stats, aes(x = 12, y = 3, label = label), hjust = 0, size = 3) + 
  geom_smooth(color = "black", se = F, method = "lm") +
  scale_color_brewer(name = "Block", palette = "Set1", direction = -1) +
  xlab("Distance between plots (m)") +
  ylab("Environmental distance") +
  scale_x_continuous(breaks = seq(0, 18, by = 3)) +
  theme_bw() +
  theme(text = element_text(size = 11),
        legend.position = "top")

environmental.p
```

Individual variable analysis
```{r}
#Remove variables with no variation and format it as a matrix
nut.mtx2 <- ward %>% 
  select(-Lime, -Texture, -H_Sat, -pH_Buffer, -Ca_Sat, -K_Sat, -Na_Sat, -Mg_Sat, -lbs) %>% 
  as.data.frame()
row.names(nut.mtx2) <- nut.mtx2$SampleID
nut.mtx2 <- nut.mtx2[,-1]
nut.mtx2 <- as.matrix(nut.mtx2)

#Function to calculate the absolute differences between pairs of samples for each parameter
get_differences <- function(x){
  vec <- nut.mtx2[,x]
  vec %*% t(vec)
  var.dist <- dist(as.matrix(data.frame(x = 0, y = vec))) %>% as.matrix()
  var.dist[upper.tri(var.dist)] <- NA 
  var.dist %>% 
    as.data.frame() %>% 
    mutate(SampleID.x = row.names(.)) %>% 
    gather(key = "SampleID.y", value = "VarDist", -SampleID.x) %>% 
    filter(!is.na(VarDist))
}

#Generate a data frame with the absolute differences and spatial distance for each parameter
var.list <- list()

for(i in 1:ncol(nut.mtx2)){
  var.name <- colnames(nut.mtx2)[i]
  var.list[[var.name]] <- get_differences(i) 
}
  
var.tidy <- plyr::ldply(var.list, function(x) x) %>% 
  filter(SampleID.x != SampleID.y) %>% 
  inner_join(map, by = c("SampleID.x" = "SampleID")) %>% 
  inner_join(map, by = c("SampleID.y" = "SampleID")) %>% 
  mutate(SpatialDistance = sqrt((Position.x.x - Position.x.y)^2 + (Position.y.x - Position.y.y)^2))
names(var.tidy)[1] <- "Variable"

#Run correlations and regressions
run_cor <- function(x){
  cor.test(x$SpatialDistance, x$VarDist, method = "pearson", alternative = "two.sided") %>% 
  tidy()
}

#Aggregate all the stats
stats <- var.tidy %>% 
  group_by(Variable) %>% 
  nest() %>% 
  mutate(cor = map(data, run_cor)) %>% 
  unnest(cor) %>% 
  ungroup() %>% 
  mutate(p.adj = p.adjust(p.value, method = "holm")) %>% 
  mutate(label = paste("r = ", signif(estimate,2), ", P = ", signif(p.adj,3), sep = "")) %>% 
  inner_join(alt.names, by = "Variable")

#Plot
variables.p <- var.tidy %>% 
  inner_join(stats, by = "Variable") %>% 
  ggplot(aes(SpatialDistance, VarDist)) +
  geom_point(shape = 16, size = 1, alpha = 0.5, color = "gray25") +
  #geom_text(data = bc.stats, aes(x = 9, y = 0.4, label = label), hjust = 0) + 
  geom_smooth(color = "black", se = F, method = "lm") +
  scale_color_brewer(name = "Block", palette = "Set1", direction = -1) +
  xlab("Distance between plots (m)") +
  ylab("Difference between samples") +
  scale_x_continuous(breaks = seq(0, 18, by = 3)) +
  facet_wrap(~ Variable2 + label, scales = "free", ncol = 4) + 
  theme_bw() +
  theme(text = element_text(size = 11),
        legend.position = "top",
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"))

variables.p
```
Put it all together
```{r}
top <- plot_grid(NA, environmental.p, NA, rel_widths = c(1,2,1), nrow = 1, labels = c(NA, "a", NA), label_size = 15)

plot_grid(top, variables.p, nrow = 2, rel_heights = c(1,3), labels = c(NA, "b"), label_size = 15)
```

