Load libraries
```{r}
library(cowplot)
library(ggrastr)
library(tidyverse)
source("../General/general_functions.R")
```

Load data
```{r}
#Load vConTACT network edges
edges <- readRDS("../Data/refseq_ind_edges.RDS")

#Load pairs of nodes involving hopland vOTUs and RefSeq viruses
pairs <- readRDS("../Data/refseq_ind_pairs.RDS")

#Load RefSeq host taxonomy
refseq.tax <- readRDS("../Data/refseq_host_tax.RDS")

#Load vConTACT network nodes
nodes <- readRDS("../Data/refseq_ind_nodes.RDS") %>% 
  left_join(refseq.tax, by = "Genome") %>%
  mutate(HostPhylum2 = ifelse(HostPhylum %in% c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria"), as.character(HostPhylum), "Other")) %>% 
  mutate(HostPhylum2 = fct_relevel(HostPhylum2, "Other")) %>% 
  mutate(Family2 = ifelse(Family %in% c("Myoviridae", "Podoviridae", "Siphoviridae"), as.character(Family), "Other")) %>% 
  mutate(Family2 = fct_relevel(Family2, "Other")) %>% 
  mutate(SourceSub = case_when(Source == "refseq" ~ "RefSeq",
                               Source == "hopland" & Subnetwork == FALSE ~ "This study",
                               TRUE ~ "Subnetwork")) 

#Define node size for plotting
node.size <- 1
```

Panel A
```{r}
ntwk.tmp.p <- nodes %>% 
  ggplot(aes(x,y)) +
  geom_line(data = edges, aes(x, y, group = Pair), color = "black", alpha = 0.1, size = 0.2) +
  geom_point(data = filter(nodes, Source == "hopland" & Subnetwork == FALSE), aes(x, y, color = SourceSub, fill = SourceSub), alpha = 1, size = node.size, shape = 16) +
  geom_point(data = filter(nodes, Source == "hopland" & Subnetwork == TRUE), aes(x, y, color = SourceSub, fill = SourceSub), alpha = 1, size = node.size, shape = 21) +
  geom_point(data = filter(nodes, Source == "refseq"), aes(x, y, color = SourceSub, fill = SourceSub), alpha = 1, size = node.size - 0.3 , shape = 16) +
  scale_fill_manual(name = "Source", values = c("red3", "gray85", "gray85"), limits = c("RefSeq", "This study", "Subnetwork")) +
  scale_color_manual(name = "Source", values = c("red3", "gray85", "black"), limits = c("RefSeq", "This study", "Subnetwork")) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5),
         color = guide_legend(title.position = "top", title.hjust = 0.5)) +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        legend.text = element_text(size = 9),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        legend.position = "none")

ntwk.p <- plot_grid(ntwk.tmp.p, get_legend(ntwk.tmp.p + theme(legend.position = "right")), ncol = 2, rel_widths = c(4,3))
ntwk.p
```

Panel B
```{r}
#Virus family palette
family.pal <- c("gray15", "gray40", rcartocolor::carto_pal(12, "Bold")[2:4])

#Network plot
family.ntwk.p <- nodes %>% 
  ggplot(aes(x,y)) +
  geom_line(data = filter(edges, Genome %in% pairs$hoplandOTU | !str_detect(Genome, "V\\d\\d_VIR")), aes(x, y, group = Pair), color = "black", alpha = 0.1, size = 0.2) +
  geom_point(data = filter(nodes, Genome %in% pairs$hoplandOTU & Source == "hopland" & Subnetwork == FALSE), aes(x, y), alpha = 1, size = node.size , shape = 16, color = "gray85") +
  geom_point(data = filter(nodes, Genome %in% pairs$hoplandOTU & Source == "hopland" & Subnetwork == TRUE), aes(x, y), alpha = 1, size = node.size , shape = 21, fill = "gray85", color = "black") +
  geom_point(data = filter(nodes, Source == "refseq"), aes(x, y, color = Family2), alpha = 1, size = node.size , shape = 16) +
  scale_color_manual(values = family.pal[-1]) +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        legend.position = "none")

#Barplot displaying the composition of the whole network and subnetwork  
family.nodes.p <-  pairs %>% 
  mutate(Family2 = ifelse(Family %in% c("Myoviridae", "Podoviridae", "Siphoviridae"), as.character(Family), "Other")) %>% 
  group_by(Set, hoplandOTU, Family2) %>% 
  count() %>% 
  group_by(Set, hoplandOTU) %>% 
  mutate(Total = n()) %>% 
  ungroup() %>% 
  mutate(Family3 = ifelse(Total == 1, as.character(Family2), "Mixed")) %>% 
  mutate(Family3 = fct_relevel(Family3, "Mixed", "Other")) %>% 
  group_by(Set, hoplandOTU, Family3) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(Set = fct_relevel(Set, "Whole network")) %>% 
  ggplot(aes(Set, fill = Family3)) +
  geom_bar(position = "fill") +
  scale_fill_manual(name = "Family", values = family.pal) +
  ylab("Fraction of nodes\nlinked to a RefSeq genome") +
  theme_minimal() +
  theme(text = element_text(size = 11),
        legend.text = element_text(size = 9),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")

family.p <-  plot_grid(family.ntwk.p, family.nodes.p, ncol = 2, rel_widths = c(4,3))

family.p
```

Panel C
```{r}
#Host taxonomy palette
host.pal <- c("gray15", "gray40", rcartocolor::carto_pal(12, "Bold")[6:9])

#Network plot
host.ntwk.p <- nodes %>% 
  ggplot(aes(x,y)) +
  geom_line(data = filter(edges, Genome %in% pairs$hoplandOTU | !str_detect(Genome, "V\\d\\d_VIR")), aes(x, y, group = Pair), color = "black", alpha = 0.1, size = 0.2) +
  geom_point(data = filter(nodes, Genome %in% pairs$hoplandOTU & Source == "hopland" & Subnetwork == FALSE), aes(x, y), alpha = 1, size = node.size , shape = 16, color = "gray85") +
  geom_point(data = filter(nodes, Genome %in% pairs$hoplandOTU & Source == "hopland" & Subnetwork == TRUE), aes(x, y), alpha = 1, size = node.size , shape = 21, fill = "gray85", color = "black") +
  geom_point(data = filter(nodes, Source == "refseq"), aes(x, y, color = HostPhylum2), alpha = 1, size = node.size , shape = 16) +
    scale_color_manual(values = host.pal[-1]) +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        legend.position = "none")

#Barplot displaying the composition of the whole network and subnetwork  
host.nodes.p <- pairs %>% 
  mutate(HostPhylum2 = ifelse(HostPhylum %in% c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria"), as.character(HostPhylum), "Other")) %>% 
  group_by(Set, hoplandOTU, HostPhylum2) %>% 
  count() %>% 
  group_by(Set, hoplandOTU) %>% 
  mutate(Total = n()) %>% 
  ungroup() %>% 
  mutate(HostPhylum3 = ifelse(Total == 1, HostPhylum2, "Mixed")) %>% 
  mutate(HostPhylum3 = fct_relevel(HostPhylum3, "Mixed", "Other")) %>% 
  group_by(Set, hoplandOTU, HostPhylum3) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(Set = fct_relevel(Set, "Whole network")) %>% 
  ggplot(aes(Set, fill = HostPhylum3)) +
  geom_bar(position = "fill") +
  scale_fill_manual(name = "Host Phylum", values = host.pal) +
  ylab("Fraction of nodes\nlinked to a RefSeq genome") +
  theme_minimal() +
  theme(text = element_text(size = 11),
        legend.text = element_text(size = 9),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right")

host.p <- plot_grid(host.ntwk.p, host.nodes.p, ncol = 2, rel_widths = c(4,3))

host.p
```

Put it all together
609:983
```{r}
left <- plot_grid(ntwk.tmp.p, family.ntwk.p, host.ntwk.p, ncol = 1, labels = c("a", "b", "c"), label_size = 15)
right <- plot_grid(get_legend(ntwk.tmp.p + theme(legend.position = "right")), family.nodes.p, host.nodes.p, ncol = 1, align = "v", axis = "lr")
plot_grid(left, right, ncol = 2, rel_widths = c(4,3))
```




