Load libraries
```{r}
library(broom)
library(cowplot)
library(tidyverse)
source("../General/general_functions.R")
```

Load data
```{r}
#Generate palette
ntwk.palette = c(rcartocolor::carto_pal(7, "Tropic")[2], "gray85", rcartocolor::carto_pal(7, "Tropic")[7])

#Load mapping file and reformat
map <- readRDS("../Data/map.RDS") %>% 
  rename("SampleID" = "ViromeSampleID") %>% 
  filter(SampleID != "V33") %>% 
  mutate(Block = ifelse(Block == "Upper", "Upper block", "Lower block")) %>% 
  mutate(Block = fct_relevel(Block, "Upper block")) 

#Load OTU table and remove singletons
otu <- readRDS("../Data/votu_tmean75.RDS")
otu <- otu[,match(map$SampleID, colnames(otu))]
otu <- otu[rowSums(otu>0)>1,]

#Load indicator species results
response <- readRDS("../Data/votu_indicator.RDS")

#Load deseq model for position along the field
deseq <- readRDS("../Data/votu_deseq_position.RDS")

#Load T2-50 subnetwork data
subnetwork <- readRDS("../Data/safe_ind_subntwk_nodes.RDS")

#Load occupancy data frame
occupancy.df <- readRDS("../Data/votu_occupancy.RDS")
```

Panel A
```{r}
#Generate a data frame with the absence/presence data and annotate it with the indicator species results and the spatial trends captured by the deseq model
presence.df <- otu %>% 
  rel_ab() %>% 
  tidy_otu() %>% 
  inner_join(response, by = "OTU_ID") %>% 
  inner_join(map, by = "SampleID") %>% 
  mutate(Subnetwork = OTU_ID %in% subnetwork$Genome) %>% 
  group_by(Block, Plot, Response, Subnetwork, OTU_ID) %>%
  summarise(AggRelAb = mean(Count)) %>%
  ungroup() %>% 
  mutate(Presence = AggRelAb > 0) %>% 
  inner_join(deseq, by = "OTU_ID")

#Plot a heatmap identifying each of the subnetwork vOTUs along the spatial gradient
response.p <- presence.df  %>% 
  group_by(OTU_ID, Response, Subnetwork, estimate) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(Response2 = ifelse(Response == "Dry" & Subnetwork, "Enriched\nin T2-50",  "NS")) %>% 
  ggplot(aes(Response2, reorder(OTU_ID, estimate), color = Response2)) +
  geom_point(size = 2, shape = 95) +
  scale_color_manual(values = ntwk.palette[c(3,2,1)]) + 
  ylab("vOTU") +
  theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text.y = element_blank(),
        #axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        legend.position = "none")

#Plot a heatmap with the presence/absence data
heatmap.p <- presence.df %>% 
  ggplot(aes(Plot, reorder(OTU_ID, estimate), fill = Presence)) +
  geom_tile() +
  facet_grid(. ~ Block, scales = "free", space = "free") +
  scale_fill_manual(values = c("white", "gray25")) +
  theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"),
        legend.position = "none")

a <- plot_grid(response.p, heatmap.p, nrow = 1, rel_widths = c(1,9), align = "h", axis = "bt")
a
```
Panel B
```{r}
b <- occupancy.df %>% 
  inner_join(response, by = "OTU_ID") %>% 
  filter(Response == "Dry") %>% 
  filter(OTU_ID %in% subnetwork$Genome) %>% 
  mutate(Response = fct_recode(Response,
                               "Enriched in T2-50" = "Dry",
                               "Depleted in T2-50" = "Wet")) %>% 
  ggplot(aes(Occupancy, fill = Response)) +
  geom_bar(position = "stack") +
  scale_fill_manual(values = ntwk.palette[c(3,2,1)]) +
  #facet_grid(Response ~ .) +
  xlim(0,43) +
  ylab("Number of vOTUs") +
  xlab("Occupancy (# of samples)") +
  theme_bw() +
  theme(text = element_text(size = 12),
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"),
        legend.position = "none")
b
```

730:450
```{r}
plot_grid(response.p, heatmap.p, b, nrow = 1, rel_widths = c(1,7,5), align = "h", axis = "bt", labels = c("a", NA, "b"), label_size = 15)
```







