Load libraries
```{r}
library(RColorBrewer)
library(cowplot)
library(broom)
library(tidyverse)
```

Load data and reformat
```{r}
#Generate palettes
trt.pal <- brewer.pal(9, "Greys")[c(9, 4)] 
time.pal <- rcartocolor::carto_pal(10, "Bold")[c(3,4)]

#Load vOTU PCoA scores and eigenvalues
v.pcoa.axes <- readRDS("../Data/votu_pcoa_axes.RDS") %>% mutate(Set = "vOTUs")
v.pcoa.eigval <- readRDS("../Data/votu_pcoa_eigval.RDS") %>% mutate(Set = "vOTUs")

#Load amplicon PCoA scores and eigenvalues
b.pcoa.axes <- readRDS("../Data/bac_otu97_pcoa_axes.RDS") %>% mutate(Set = "16S rRNA gene OTUs")
b.pcoa.eigval <- readRDS("../Data/bac_otu97_pcoa_eigval.RDS") %>% mutate(Set = "16S rRNA gene OTUs")
```

Panel A & B
```{r}
a <- v.pcoa.axes %>% 
  ggplot(aes(Axis.1, Axis.2)) +
  geom_point(aes(fill = WaterTreatment, shape = Timepoint), size = 2, stroke = 0.5, alpha = 1, shape = 21) +
  xlab(paste("PCo1 (", v.pcoa.eigval$Eigval[1], "%)", sep = "")) +
  ylab(paste("PCo2 (", v.pcoa.eigval$Eigval[2], "%)", sep = "")) +
  scale_fill_manual(name = "Rainfall treatment", values = trt.pal) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  facet_wrap(~ Set) +
  theme_bw() +
  theme(text = element_text(size = 11),
        legend.position = "top",
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"))

b <- v.pcoa.axes %>% 
  ggplot(aes(Axis.1, Axis.2)) +
  geom_line(aes(group = Subplot), linetype = 2, color = "gray75") +
  geom_point(aes(fill = Timepoint), size = 2, stroke = 0.5, alpha = 1, shape = 21) +
  xlab(paste("PCo1 (", v.pcoa.eigval$Eigval[1], "%)", sep = "")) +
  ylab(paste("PCo2 (", v.pcoa.eigval$Eigval[2], "%)", sep = "")) +
  scale_fill_manual(name = "Time point", values = time.pal) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  facet_wrap(~ Set) +
  theme_bw() +
  theme(text = element_text(size = 11),
        legend.position = "top",
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"))
```

Panel C & D
```{r}
c <- b.pcoa.axes %>% 
  mutate(WaterTreatment = fct_recode(WaterTreatment,
                                     "100%" = "Full",
                                     "50%" = "Half")) %>%
  mutate(WaterTreatment = fct_relevel(WaterTreatment, "100%")) %>% 
  ggplot(aes(Axis.1, Axis.2)) +
  geom_point(aes(fill = WaterTreatment, shape = Timepoint), size = 2, stroke = 0.5, alpha = 1, shape = 21) +
  xlab(paste("PCo1 (", b.pcoa.eigval$Eigval[1], "%)", sep = "")) +
  ylab(paste("PCo2 (", b.pcoa.eigval$Eigval[2], "%)", sep = "")) +
  scale_fill_manual(name = "Rainfall treatment", values = trt.pal) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  facet_wrap(~ Set) +
  theme_bw() +
  theme(text = element_text(size = 11),
        legend.position = "top",
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"))

d <- b.pcoa.axes %>% 
  mutate(Timepoint = fct_recode(Timepoint,
                                     "March (T1)" = "T1",
                                     "April (T2)" = "T2")) %>%
  mutate(Timepoint = fct_relevel(Timepoint, "March (T1)")) %>% 
  ggplot(aes(Axis.1, Axis.2)) +
  geom_line(aes(group = Subplot), linetype = 2, color = "gray75") +
  geom_point(aes(fill = Timepoint, shape = Timepoint), size = 2, stroke = 0.5, alpha = 1, shape = 21) +
  xlab(paste("PCo1 (", b.pcoa.eigval$Eigval[1], "%)", sep = "")) +
  ylab(paste("PCo2 (", b.pcoa.eigval$Eigval[2], "%)", sep = "")) +
  scale_fill_manual(name = "Time point", values = time.pal) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  facet_wrap(~ Set) +
  theme_bw() +
  theme(text = element_text(size = 11),
        legend.position = "top",
        strip.background =element_rect(fill="gray25"),
        strip.text = element_text(colour = "white"))
```

492:552
```{r}
plot_grid(get_legend(c),
          get_legend(d),
          a + theme(legend.position = "none"),
          b + theme(legend.position = "none"),
          c + theme(legend.position = "none"),
          d + theme(legend.position = "none"),
          nrow = 3, rel_heights = c(1,4,4), labels = c(NA, NA, "a","b","c","d"), label_size = 15)
```

