Load libraries
```{r}
library(lubridate)
library(cowplot)
library(RColorBrewer)
library(tidyverse)
```

Load data and reformat
```{r}
#Generate palette
trt.pal <- brewer.pal(9, "Greys")[c(9, 4)] 

#Precipitation data
ppt <- read.table("../Data/precipitation.tsv", header = T, sep = "\t") %>% 
  gather(key = "Variable", value = "Value", Temp_2021:Rain_2018) %>% 
  separate(Variable, c("Variable", "Year")) %>% 
  filter(Variable == "Rain") %>% 
  mutate(Value = ifelse(Value == "N/A", NA, Value)) %>% 
  mutate(Value = as.numeric(Value)) %>% 
  mutate(Date = make_date(year = Year, month = Month, day = Day))

#Shelter schedule
shelters <- read.table("../Data/shelters.tsv", header = T, sep = "\t") %>% 
  mutate(Start = mdy(Start),
         End = mdy(End)) %>% 
  mutate(WaterTreatment = fct_recode(WaterTreatment,
                                     "100%" = "Full",
                                     "50%" = "Half"))

#Irrigation regimes
watering <- read.table("../Data/watering.tsv", header = T, sep = "\t") %>% 
  mutate(Date = mdy(Date)) %>% 
  filter(Event == "Watering") %>% 
  gather(key = "Event", value = "Amount", Amount_100:Amount_50) %>% 
  mutate(WaterTreatment = ifelse(Event == "Amount_100", "Full", "Half")) %>% 
  mutate(Event = "Watering") %>% 
  select(Date, Event, WaterTreatment, Amount) %>% 
  filter(Amount > 0) %>% 
  mutate(WaterTreatment = fct_recode(WaterTreatment,
                                     "100%" = "Full",
                                     "50%" = "Half"))

#Collection time points
collection <- data.frame(Date = c(ymd("2020-03-12"), ymd("2020-04-13")),
                         Label = c("T1", "T2"))

#Generate plot map from mapping file
map <- readRDS("../Data/map.RDS")
plot.map <- map %>% 
  group_by(Plot, Position.x, Position.y, Block, WaterTreatment) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(Cores = n/2) %>% 
  mutate(WaterTreatment = ifelse(WaterTreatment == "Full", "100%", "50%"))

#Avena growth data
avena <- readRDS("../Data/avena.RDS") %>% 
  mutate(PlotNum = as.integer(str_remove(Plot, "P"))) %>% 
  mutate(Plot = ifelse(PlotNum < 10, paste("P0", PlotNum, sep = ""), paste("P", PlotNum, sep = ""))) %>% 
  select(Date, Plot, MeanHeight) %>% 
  inner_join(plot.map) %>% 
  mutate(Date = as.Date(Date))
```


Panel A
```{r}
map.p <- plot.map %>% 
  ggplot(aes(Position.x, Position.y, fill = WaterTreatment)) +
  geom_point(shape = 22, size = 10, stroke = 2, aes(color = WaterTreatment)) +
  geom_text(data = filter(plot.map, WaterTreatment == "100%"), aes(label = Cores), color = "white") +
  geom_text(data = filter(plot.map, WaterTreatment == "50%"), aes(label = Cores), color = "black") +
  scale_fill_manual(name = "Rainfall\ntreatment", values = trt.pal) +
  scale_color_manual(name = "Rainfall\ntreatment", values = trt.pal) +
  theme_minimal() +
  theme(text = element_text(size = 12),
        axis.title = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        legend.position = c(0.8,0.3))
map.p
```

Panel C
```{r}
rainfall.p <- ppt %>% 
  filter(Date > ymd("2019-09-15")) %>% 
  filter(Date < ymd("2020-05-01")) %>% 
  ggplot() +
  geom_rect(data = filter(shelters, WaterTreatment == "50%"), aes(xmin = Start, xmax = End, ymin = -0.1, ymax = 1.3 * 25.4, fill = WaterTreatment)) +
  geom_rect(data = filter(shelters, WaterTreatment == "100%"), aes(xmin = Start, xmax = End, ymin = -0.1, ymax = 1.25 * 25.4, fill = WaterTreatment)) +
  geom_line(aes(Date, Value * 25.4), color = "deepskyblue4", size = 1) +
  geom_point(data = collection, aes(x = Date, y = 0.5 * 25.4), shape = 25, size = 3) +
  geom_text(data = collection, aes(x = Date, y = 0.6 * 25.4, label = Label),size = 3, angle = 0, hjust = 0.5) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b", limits = c(ymd("2019-09-15"),ymd("2020-05-01"))) +
  #xlim(c(ymd("2019-09-15"),ymd("2020-05-01"))) +
  ylab("Daily rainfall (mm)") +
  scale_fill_manual(name = "Shelters\ninstalled",
                    values = trt.pal) +
  theme_bw() +
  theme(text = element_text(size = 12),
        legend.position = "none")

rainfall.p
```
Panel D
```{r}
tmp <- data.frame(Date = c(as.Date("2020-01-02"), as.Date("2020-01-10"), as.Date("2020-01-23")),
           Event = c("Watering","Watering","Watering"),
           WaterTreatment = c("50%","50%","50%"),
           Amount = c(0,0,0))

watering.p <- watering %>% 
  rbind(tmp) %>% 
  ggplot() +
  geom_bar(aes(x = Date, y = Amount * 3.78541, fill = WaterTreatment), stat = "identity", position = "dodge", width = 4, preserve = "single") +
  geom_point(data = collection, aes(x = Date, y = 100), shape = 25, size = 3) +
  geom_text(data = collection, aes(x = Date, y = 125, label = Label),  size = 3, angle = 0, hjust = 0.5) +
  scale_fill_manual(name = "Treatment", values = trt.pal) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b", limits = c(ymd("2019-09-15"),ymd("2020-05-01"))) +
  #xlim(c(ymd("2019-09-15"),ymd("2020-05-01"))) +
  ylab("Watering (l)") +
  theme_bw() +
  theme(text = element_text(size = 12),
        legend.position = "none")

watering.p
```

Panel E
```{r}
avena.p <- avena %>% 
  filter(Date < ymd("2020-05-01")) %>% 
  ggplot() +
  geom_point(aes(Date, MeanHeight, color = WaterTreatment)) +
  geom_line(aes(Date, MeanHeight, color = WaterTreatment, Group = Plot)) +
  geom_point(data = collection, aes(x = Date, y = 64), shape = 25, size = 3) +
  geom_text(data = collection, aes(x = Date, y = 70, label = Label), size = 3, angle = 0, hjust = 0.5) +
  scale_color_manual(name = "Treatment", values = trt.pal) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b", limits = c(ymd("2019-09-15"),ymd("2020-05-01"))) +
  #xlim(c(ymd("2019-09-15"),ymd("2020-05-01"))) +
  #ylim(10,80) +
  ylab("Plant height (cm)") +
  theme_bw() +
  theme(text = element_text(size = 12),
        legend.position = "none")

avena.p
```

682:976
```{r}
bottom.p <- plot_grid(rainfall.p, watering.p, avena.p, align = "v", axis = "lr", nrow = 3, labels = c("c", "d", "e"), label_size = 15)

bottom.p

top.p <-  plot_grid(map.p, NA, rel_widths = c(3,2), labels = c("a", "b"), label_size = 15)

plot_grid(top.p, bottom.p, rel_heights = c(1,2), nrow = 2)
```

