Load libraries
```{r}
library(tidyverse)
source("../General/general_functions.R")
```

Load data
```{r}
#Load mapping file
map <- readRDS("../Data/map.RDS") %>% 
  rename("SampleID" = "ViromeSampleID") %>% 
  filter(SampleID != "V33") 

#Load OTU table and remove singletons
otu <- readRDS("../Data/votu_tmean75.RDS")
otu <- otu[,match(map$SampleID, colnames(otu))]
otu <- otu[rowSums(otu>0)>1,]

#Normalize OTU table
otu.norm <- otu %>% rel_ab() %>% log_norm()
```

Define the occupancy threshold at which 50% of vOTUs are accounted for
```{r}
occupancy.df <- otu %>% 
  rel_ab() %>% 
  tidy_otu() %>% 
  group_by(OTU_ID) %>% 
  summarise(Occupancy = sum(Count > 0),
            MeanRelAb = mean(Count)) 

occupancy.df %>% 
  group_by(Occupancy) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(Percent = n/sum(n)) %>% 
  mutate(CumSum = cumsum(Percent))

#Save occupancy data frame
saveRDS(occupancy.df, "../Data/votu_occupancy.RDS")
```

Peform principal coordinates analysis
```{r}
#Calculate BC dissimilarities
bc.dist <- beta_div_dist(otu.norm)

#Perform PCoA
bc.pcoa.axes <- pcoa_axes(bc.dist, map)
bc.pcoa.eigval <- pcoa_eigval(bc.dist, map)

#Save results
saveRDS(bc.pcoa.axes, "../Data/votu_pcoa_axes.RDS")
saveRDS(bc.pcoa.eigval, "../Data/votu_pcoa_eigval.RDS")
```

Generate long data frame with BC dissimilarities
```{r}
#Remove redundant datapoints
bc.dist[upper.tri(bc.dist)] <- NA 

#Reformat
bc.dist.tidy <- bc.dist %>% 
  as.data.frame() %>% 
  mutate(SampleID.x = rownames(.)) %>% 
  gather(key = "SampleID.y", value = "Distance", -SampleID.x) %>% 
  inner_join(map, by = c("SampleID.x" = "SampleID")) %>% 
  inner_join(map, by = c("SampleID.y" = "SampleID")) %>% 
  filter(!is.na(Distance))

#Save results
saveRDS(bc.dist.tidy, "../Data/votu_braycurtis_tidy.RDS")
```


Generate overlap datafram
```{r}
#Generate presence/absence vOTU table
bi.otu <- otu > 0

#Find the number of vOTUs overlapping between pairs of samples. %*% indicates that this should be treated as a matrix multiplication in linear algebra
overlap <- t(bi.otu) %*% (bi.otu)

#The universe of vOTUs shared by a pair of samples is the  sum of the overlap and the number of vOTus unique to each of the samples.  
total <- (colSums(bi.otu) - overlap) + t(colSums(bi.otu) - overlap) + overlap

#Caclulate the percent of vOTUs shared
pct.shared <- overlap / total

#Remove redudndant data points
pct.shared[upper.tri(pct.shared)] <- NA

#Generate data frame
pct.tidy <- pct.shared %>% 
  as.data.frame() %>% 
  mutate(SampleID.x = row.names(.)) %>% 
  gather(key = "SampleID.y", value = "PercentShared", -SampleID.x) %>% 
  filter(!is.na(PercentShared)) %>% 
  inner_join(map, by = c("SampleID.x" = "SampleID")) %>% 
  inner_join(map, by = c("SampleID.y" = "SampleID")) %>% 
  mutate(Difference = abs(PlotNum.x - PlotNum.y)) 

#Save results
saveRDS(pct.tidy, "../Data/votu_overlap.RDS")
```


